# Lab #3 Exercise
### COMM 4259 <br> <i>Foundations of Machine Learning and AI</i>


© Jingjing Li- Ask for permission for using/quoting: jingjing.li@virginia.edu

## Data Analysis

You need to analyze the fortune500.csv data. This is a data set of Fortune 500 companies spanning over 50 since 1955, put together from Fortune’s public archive.

### 1. Read data and obtain the shape

In [26]:
import pandas as pd

url = "fortune500.csv"
df = pd.read_csv(url)
type(df)

df.shape

(25131, 5)

### 2. Read top 3 rows

In [27]:
df.head(3)

   Year  Rank         Company  Revenue (in millions)  Profit (in millions)
0  1955     1  General Motors                 9823.5                 806.0
1  1955     2     Exxon Mobil                 5661.4                 584.8
2  1955     3      U.S. Steel                 3250.4                 195.4

### 3. Show the company column (use dot and bracket notation)

In [28]:
df.Company

0               General Motors
1                  Exxon Mobil
2                   U.S. Steel
3             General Electric
4                       Esmark
                 ...
25126          Wm. Wrigley Jr.
25127           Peabody Energy
25128    Wendy's International
25129       Kindred Healthcare
25130     Cincinnati Financial
Name: Company, Length: 25131, dtype: str

In [29]:
df["Company"]

0               General Motors
1                  Exxon Mobil
2                   U.S. Steel
3             General Electric
4                       Esmark
                 ...
25126          Wm. Wrigley Jr.
25127           Peabody Energy
25128    Wendy's International
25129       Kindred Healthcare
25130     Cincinnati Financial
Name: Company, Length: 25131, dtype: str

### 4. Get column names

In [30]:
df.columns

Index(['Year', 'Rank', 'Company', 'Revenue (in millions)',
       'Profit (in millions)'],
      dtype='str')

### 5. Rename column
Rename "'Revenue (in millions)" to be "Revenue_millions" and "Profit (in millions)" to be "Profit_millions"

In [31]:
df.rename(columns= {'Revenue (in millions)' : 'Revenue_millions'}, inplace = True)
df.rename(columns= {'Profit (in millions)' : 'Profit_millions'}, inplace= True)

df.head()

   Year  Rank           Company  Revenue_millions  Profit_millions
0  1955     1    General Motors            9823.5            806.0
1  1955     2       Exxon Mobil            5661.4            584.8
2  1955     3        U.S. Steel            3250.4            195.4
3  1955     4  General Electric            2959.1            212.6
4  1955     5            Esmark            2510.8             19.1

### 6. Get column types

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25131 entries, 0 to 25130
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              25131 non-null  int64
 1   Rank              25131 non-null  int64
 2   Company           25131 non-null  str
 3   Revenue_millions  25131 non-null  float64
 4   Profit_millions   25131 non-null  float64
dtypes: float64(2), int64(2), str(1)
memory usage: 1.3 MB

### 7. Get the company column use loc function.

In [33]:
df.loc[:, "Company"]

0               General Motors
1                  Exxon Mobil
2                   U.S. Steel
3             General Electric
4                       Esmark
                 ...
25126          Wm. Wrigley Jr.
25127           Peabody Energy
25128    Wendy's International
25129       Kindred Healthcare
25130     Cincinnati Financial
Name: Company, Length: 25131, dtype: str

### 8. Get company name and profit in the first row

In [34]:
df.loc[0, ["Company", "Profit_millions"]]

Company            General Motors
Profit_millions             806.0
Name: 0, dtype: object

### 9. Get all  rows with profit greater than 100 (millions)

In [35]:
df.loc[df.Profit_millions > 100]

,Year,Rank,Company,Revenue_millions,Profit_millions
0,1955,1,General Motors,9823.5,806.0
1,1955,2,Exxon Mobil,5661.4,584.8
2,1955,3,U.S. Steel,3250.4,195.4
3,1955,4,General Electric,2959.1,212.6
7,1955,8,Gulf Oil,1705.3,182.8
...,...,...,...,...,...
25122,2005,492,Brinker International,3707.5,154.0
25124,2005,494,Western & Southern Financial,3694.5,328.0
25126,2005,496,Wm. Wrigley Jr.,3648.6,493.0
25127,2005,497,Peabody Energy,3631.6,175.4
25130,2005,500,Cincinnati Financial,3614.0,584.0

### 10. Get all rows with profit greater than 5,000 (millions) in 2000

In [36]:
df.loc[(df.Profit_millions > 5000) & (df.Year == 2000)]

       Year  Rank                  Company  Revenue_millions  Profit_millions
22148  2000     1           General Motors          189058.0           6002.0
22149  2000     2          Wal-Mart Stores          166809.0           5377.0
22150  2000     3              Exxon Mobil          163881.0           7910.0
22151  2000     4               Ford Motor          162558.0           7237.0
22152  2000     5         General Electric          111630.0          10717.0
22153  2000     6  Intl. Business Machines           87548.0           7712.0
22154  2000     7                Citigroup           82005.0           9867.0
22156  2000     9             Altria Group           61751.0           7675.0
22158  2000    11    Bank of America Corp.           51392.0           7882.0
22159  2000    12       SBC Communications           49489.0           8159.0
22164  2000    17     American Intl. Group           40656.1           5055.4
22178  2000    31    Chase Manhattan Corp.           33710.0           5446.0
22181  2000    34                    Merck           32714.0           5890.5
22186  2000    39                    Intel           29389.0           7314.0
22189  2000    42                   DuPont           27892.0           7690.0
22231  2000    84                Microsoft           19747.0           7785.0

### 11. Get the company names with profit greater than 5,000 (millions) in 2000

In [37]:
df.loc[(df.Profit_millions > 5000) & (df.Year == 2000), "Company"]

22148             General Motors
22149            Wal-Mart Stores
22150                Exxon Mobil
22151                 Ford Motor
22152           General Electric
22153    Intl. Business Machines
22154                  Citigroup
22156               Altria Group
22158      Bank of America Corp.
22159         SBC Communications
22164       American Intl. Group
22178      Chase Manhattan Corp.
22181                      Merck
22186                      Intel
22189                     DuPont
22231                  Microsoft
Name: Company, dtype: str

### 12. Get the last three columns of the second to fifth row (use iloc)

### 13. Describe the Profit and Revenue

### 14. Get the frequency table for the variable Year

### 15. Draw a histogram of profit in the year of 2000

### 16. Create a dataframe for Microsoft and Oracle. Draw a boxplot with the x axis showing two companies and y axis showing profit.

### 17. Draw two histograms side by side showing the profit for Microsoft and Oracle (FacetGrid)

### 18. Draw a line plot for Microsoft and Oracle
Create a lineplot to show Microsoft and Oracle's profit trend by year. Check the lineplot usage about x, y, and hue [here](https://seaborn.pydata.org/generated/seaborn.lineplot.html)